services:
  db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 08062002
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    image: task-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    ports:
      - "9092:9092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 08062002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
