name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring app as test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew  # Grant execute permission

      - name: Unit Testing
        run: ./gradlew test --no-daemon --console=plain

      - name: Build app
        run: |
          ./gradlew clean
          ./gradlew build --no-daemon --console=plain
